apiVersion: v1
kind: Service
metadata:
  labels:
    service: gatekeeper
  name: gatekeeper
spec:
  ports:
  - name: http
    port: 5081
    targetPort: 5081
  selector:
    service: gatekeeper
status:
  loadBalancer: {}
