apiVersion: v1
kind: ConfigMap
metadata:
  name: gatekeeper
data:
  gatekeeper.ini: |
    [DEFAULT]
    debug = True
    verbose = True

    [api]
    auth = True
    port = 5081

    [database]
    connection = mysql+pymysql://gatekeeper:gatekeeper@mysql/gatekeeper
    #connection_debug = 50
    #connection_trace = True

    [rethinkdb]
    host = 172.17.0.2

    [mqtt]
    host = 127.0.0.1
    port = 1883
    # key = "client.key"
    # cert = "client.cert"

    [integration.particle]
    webhook_token = mysecret
    client_id = clientid
    client_secret = clientsecret
