apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mysql
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: gatekeeper
        - name: MYSQL_USER
          value: gatekeeper
        - name: MYSQL_PASSWORD
          value: gatekeeper
        image: mysql
        name: mysql
        resources: {}
      restartPolicy: Always
status: {}
