apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: mysql
  name: mysql
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: mysql
status:
  loadBalancer: {}
